name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: matrix.platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Git Checkout
        uses: actions/checkout@v3


      - name: Build Docker
        run: docker build --platform ${{ matrix.platform }} . -t toto
        
      - name: Docker run toto
        run: docker run --rm toto


